  ##Sunrise
  - alias: "Sunrise"
    trigger:
      - platform: time
        hours: 6
        minutes: 25
        seconds: 0
    condition:
      - condition: state
        entity_id: input_boolean.sunrise
        state: 'on'
    action:
      service: script.turn_on
      entity_id: script.sunrise
