homeassistant:
  name: Home
  latitude: 56.1972
  longitude: 10.248
  # Impacts weather/sunrise data
  elevation: 4
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Copenhagen

  ###################
  ## CUSTOMIZATION ##
  ###################

  customize:
    script.sunrise:
      icon: mdi:duck

    switch.benq:
      icon: mdi:projector

    #HIDE
    media_player.rasplex:
      hidden: true
    scene.livingroom_dim:
      hidden: true
    scene.livingroom_normal:
      hidden: true
    script.awaken:
      hidden: true
    script.sunset:
      hidden: true
    script.moviemodeon:
      hidden: true
    automation.awaken:
      hidden: true
    automation.paused:
      hidden: true
    automation.playing:
      hidden: true
    automation.mmOff:
      hidden: true
    automation.mmOn:
      hidden: true
    automation.sunset:
      hidden: true


frontend:
http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD

#updater:
history:
logbook:
#sun:

#############
## SENSORS ##
#############
#sensor:
# Weather Prediction
  #platform: yr

##################
## MODULES INIT ##
##################
##Setup hue lights
light:
  platform: hue
  host: 192.168.1.108
  allow_unreachable: true

scene:
  - name: Livingroom normal
    entities:
        light.Corner:
            state: on
            transition: 10
            brightness: 30
            xy_color: [ 0.4448, 0.4066 ]
  - name: Livingroom dim
    entities:
        light.Corner:
            state: off
            transition: 3
        light.Loft:
            state: off
            transition: 3

switch:
  - platform: command_line
    switches:
      benq:
        command_on: "/usr/bin/curl -X GET http://192.168.1.109/benqOn"
        command_off: "/usr/bin/curl -X GET http://192.168.1.109/benqOff"
        friendly_name: BenQ
#  - platform: template
#    switches:
#      pioneer:
#        friendly_name: 'pioneer'
#        value_template: '{{ is_state('switch.benq', 'on') }}'
#        turn_on:
#          service: media_player.turn_on
#          entity_id: media_player.pioneer
#        turn_off:
#          service: media_player.turn_off
#          entity_id: media_player.pioneer

##Setup media players
media_player:
- platform: pioneer
  host: 192.168.1.106
  name: pioneer
- platform: plex
  name: rasplex
  scan_interval: 3

############
## Groups ##
############
group:
  light_automation:
    name: Light automation
    entities:
      - script.sunrise
      - input_boolean.alarm
      - input_boolean.sunset
      - input_boolean.movie_fade
  media:
    name: Media
    icon: mdi:movie
    entities:
      - input_boolean.mm
      - switch.benq
      - media_player.pioneer

############
## INPUTS ##
############
input_boolean:
  alarm:
    name: Sunrise
    icon: mdi:weather-sunset
    initial: on
  sunset:
    name: Sunset
    icon: mdi:brightness-4
    initial: on
  movie_fade:
    name: Movie fade
    icon: mdi:spotlight
    initial: on
  mm:
    name: Movie mode
    icon: mdi:movie
    initial: off

#############
## SCRIPTS ##
#############
script:
  ### Setup wake up script ###
  sunrise:
    alias: Carpe diem
    sequence:
      - alias: Kill fake sun
        service: light.turn_off
        data:
          entity_id: light.Seng
      - alias: Initial fade
        service: light.turn_on
        data:
          entity_id: light.Corner
          brightness: 100
          transition: 20
          xy_color: [ 0.4704, 0.4127 ]
      - alias: Toilet lights on
        service: light.turn_on
        data:
          entity_id: light.Toilet
          brightness: 80
          transition: 10
      - delay:
          seconds: 20
      - alias: Secondary fase
        service: light.turn_on
        data:
          entity_id: light.Corner
          brightness: 255
          transition: 2700
          xy_color: [ 0.3833, 0.3785 ]
      - alias: Secondary fase
        service: light.turn_on
        data:
          entity_id: light.Toilet
          brightness: 255
          transition: 2700

  awaken:
    alias: Wake me up with my fake sun
    sequence:
      - alias: Initial fade
        service: light.turn_on
        data:
          entity_id: light.Seng
          brightness: 1
          transition: 10
      - delay:
          minutes: 10
      - alias: Turn to 50%
        service: light.turn_on
        data:
          entity_id: light.Seng
          brightness: 128
          transition: 60
      - delay:
          minutes: 10
      - alias: Turn to 100%
        service: light.turn_on
        data:
          entity_id: light.Seng
          brightness: 255
          transition: 60

  sunset:
    alias: Sunset
    sequence:
      - alias: Fade corner out slowly
        service: light.turn_on
        data:
          entity_id: light.Corner
          brightness: 0
          transition: 6553
          xy_color: [ 0.678, 0.32 ]

  moviemodeon:
    alias: Moviemode
    sequence:
      - alias: Turn on pioneer
        service: media_player.turn_on
        data:
          entity_id: media_player.pioneer
      - delay:
          seconds: 10
      - alias: Turn on projector
        service: switch.turn_on
        data:
          entity_id: switch.benq
      - alias: Switch to tuner
        service: media_player.select_source
        data:
          entity_id: media_player.pioneer
          source: TUNER
      - delay:
          seconds: 1
      - alias: Turn up volume
        service: media_player.volume_set
        data:
          entity_id: media_player.pioneer
          volume_level: 0.8
      - delay:
          seconds: 1
      - alias: Switch to RPI
        service: media_player.select_source
        data:
          entity_id: media_player.pioneer
          source: RPI
      - delay:
          seconds: 1
      - alias: Turn down volume
        service: media_player.volume_set
        data:
          entity_id: media_player.pioneer
          volume_level: 0.7



#################################
## Setup movie mode automation ##
#################################
automation:
  ##Dim on pause/play
  - alias: "Paused"
    trigger:
      - platform: state
        entity_id: media_player.rasplex
        from: 'playing'
    condition:
      - condition: state
        entity_id: input_boolean.movie_fade
        state: 'on'
    action:
        service: scene.turn_on
        entity_id: scene.livingroom_normal

  - alias: "Playing"
    trigger:
      - platform: state
        entity_id: media_player.rasplex
        to: 'playing'
    condition:
      - condition: state
        entity_id: input_boolean.movie_fade
        state: 'on'
    action:
        service: scene.turn_on
        entity_id: scene.livingroom_dim

  ##Fade in lights
  - alias: "Awaken"
    trigger:
      - platform: time
        hours: 6
        minutes: 00
        seconds: 0
    condition:
      - condition: state
        entity_id: input_boolean.alarm
        state: 'on'
    action:
      service: script.turn_on
      entity_id: script.awaken

  ##Fade out lights
  - alias: "Sunset"
    trigger:
      - platform: time
        hours: 19
        minutes: 0
        seconds: 0
    condition:
      - condition: state
        entity_id: input_boolean.sunset
        state: 'on'
    action:
      service: script.turn_on
      entity_id: script.sunset

  #Turn on projector and receiver
  - alias: "mmOn"
    trigger:
      - platform: state
        entity_id: input_boolean.mm
        state: 'on'
    action:
      service: script.turn_on
      entity_id: script.moviemodeon

  #Turn off projector and receiver
  - alias: "mmOff"
    trigger:
      - platform: state
        entity_id: input_boolean.mm
        state: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.benq
      - service: media_player.turn_off
        entity_id: media_player.pioneer
