homeassistant:
  name: Home
  latitude: 56.1972
  longitude: 10.248
  # Impacts weather/sunrise data
  elevation: 4
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Copenhagen
  customize: !include customize.yaml

frontend:
  themes:
    darkred:
    # Main colors that can be changed
      dark-primary-color: "#c66900"
      disabled-text-color: "#545454"
      divider-color: "rgba(255, 255, 255, 0.12)"
      light-primary-color: "#e06c6c"
      paper-card-background-color: "#1d1d1d"
      paper-grey-200: "#191919"
      paper-item-icon-color: "#d3d3d3"
      paper-listbox-background-color: "#202020"
      primary-background-color: "#303030"
      primary-color: "#d32f2f"
      primary-text-color: "#cfcfcf"
      secondary-background-color: "#131313"
      sidebar-text_-_background: "#62717b"
    # Colors based on variables, see above
      paper-card-header-color: "var(--paper-item-icon-color)"
      paper-item-icon-active-color: "var(--primary-color)"
      paper-item-icon_-_color: "var(--primary-text-color)"
      paper-listbox-color: "var(--primary-text-color)"
      paper-grey-50: "var(--primary-text-color)"
      paper-slider-active-color: "var(--primary-color)"
      paper-slider-knob-color: "var(--primary-color)"
      paper-slider-knob-start-color: "var(--primary-color)"
      paper-slider-pin-color: "var(--primary-color)"
      paper-slider-secondary-color: "var(--light-primary-color)"
      paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-button-color: "var(--primary-color)"
      paper-toggle-button-checked-bar-color: "var(--light-primary-color)"
      paper-toggle-button-unchecked-bar-color: "var(--primary-text-color)"
      secondary-text-color: "var(--primary-color)"
      table-row-background-color: "var(--paper-card-background-color)"
      table-row-alternative-background-color: "var(--sidebar-text_-_background)"

http:
#  api_password: szh34uaw
discovery:

xiaomi:
  gateways:
   - mac: 286C07F0BBF5
     key: AAA03C655DE84748

#updater:
history:
logbook:
#sun:

#Setup zones
zone:
  - name: 'Home'
    latitude: 56.1972
    longitude: 10.248
    radius: 15

#############
## SENSORS ##
#############
sensor: !include sensors.yaml


#############
## MODULES ##
#############
light: !include lights.yaml
switch: !include switches.yaml
media_player: !include media_players.yaml

############
## INPUTS ##
############
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml

########
## UX ##
########
group: !include groups.yaml
scene: !include scenes.yaml

#############
## SCRIPTS ##
#############
script: !include scripts.yaml

################
## Automation ##
################
#automation: !include automations.yaml
