homeassistant:
  name: Home
  latitude: 56.1972
  longitude: 10.248
  # Impacts weather/sunrise data
  elevation: 4
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Copenhagen
  customize: !include customize.yaml

frontend:
http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD

#updater:
history:
logbook:
#sun:

#############
## SENSORS ##
#############
#sensor:
# Weather Prediction
  #platform: yr

#############
## MODULES ##
#############
light: !include lights.yaml
switch: !include switches.yaml
media_player: !include media_players.yaml

############
## INPUTS ##
############
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml

########
## UX ##
########
group: !include groups.yaml
scene: !include scenes.yaml

#############
## SCRIPTS ##
#############
script: !include scripts.yaml

################
## Automation ##
################
automation: !include automations.yaml
